website/views.py
from operator import truediv
from . import db,mail
from .models import bookingdb
from .models import User,Data
from .models import Data
from .models import galleryImageUpload
from flask import Blueprint, render_template, request,redirect, flash,url_for
from sqlalchemy import create_engine
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from flask_login import login_user,LoginManager, login_required, logout_user, current_user
import base64
import io
import re
from types import new_class
from werkzeug.security import generate_password_hash,check_password_hash
from flask import Blueprint,render_template,request,flash,jsonify,redirect,url_for
from distutils.log import debug
from email import message
from sre_constants import SUCCESS
from flask import Flask,render_template,request

from flask_mail import Mail,Message

def render_picture(data):
    render_pic=base64.b64encode(data).decode('ascii')
    return render_pic


views = Blueprint('views', __name__)
 
#login


class RegisterForm(FlaskForm):
    username=StringField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"username"})
    password=PasswordField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"password"})
    submit=SubmitField("Register")

    def validate_username(self, username):
        existing_user_username=User.query.filter_by(
            username=username.data).first()
        if existing_user_username:
            raise ValidationError("The username already exists. Please enter different username")

class LoginForm(FlaskForm):
    username=StringField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"username"})
    password=PasswordField(validators=[InputRequired(),Length(min=4,max=20)],render_kw={"placeholder":"password"})
    submit=SubmitField("Login")

@views.route("/")
def index():
    return render_template("home.html",user=current_user)


@views.route("/home")
def home():
    return render_template("home.html",user=current_user)

@views.route("/services")
def services():
    return render_template("services.html",user=current_user)



@views.route("/gallery")
def gallery():
    all_data=galleryImageUpload.query.all()
    return render_template("gallery.html",user=current_user,data=all_data)


@views.route("/login",methods=['get','post'])
def login():
    form= LoginForm()
    return render_template("login.html",form=form,user=current_user)

@views.route("/register",methods=['get','post'])
def register():
    form=RegisterForm()
    return render_template("register.html",form=form,user=current_user)

@views.route("/registerForm",methods=['get','post'])
def registerForm():
    if request.method=='POST':
        form=RegisterForm()
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            print(user)
            if user:
                flash("Username alreay exists!! Try another name")
                return redirect(url_for('views.register',user=current_user))
            else:
                new_user=User(username=form.username.data, password=form.password.data, usertype="user")
                db.session.add(new_user)
                db.session.commit()
                user = User.query.filter_by(username=form.username.data).first()
                login_user(user,remember=True)
                return redirect(url_for('views.home',user=current_user))
        return render_template("register.html",form=form,user=current_user)


@views.route("/loginForm",methods=['get','post'])
def loginForm():
    if request.method=='POST':
        form=LoginForm()
        if form.validate_on_submit():
            user = User.query.filter_by(username=form.username.data).first()
            if user:
                if(user.password == form.password.data):
                    login_user(user,remember=True)
                    if(user.usertype == "user"):
                        return redirect(url_for('views.home',user=current_user))
                    else:
                        return redirect(url_for('views.galleryAdmin',user=current_user))
                else:
                    flash("Invalid Password")
                    return redirect(url_for('views.login',user=current_user))
            else:
                flash("Username not found!!")
                return redirect(url_for('views.login',user=current_user))
        return render_template("register.html",form=form,user=current_user)

@views.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.login',user=current_user))

@views.route("/package")
def package():
    return render_template("package.html",user=current_user)


@views.route("/booking",methods=['GET','POST'])
@login_required
def booking():
    email=''
    if request.method=='POST':
        email=request.form['email']
        # print(email)
        # print("Hello")
    all_data=bookingdb.query.filter_by(username=current_user.username)
    print(current_user.username)
    return render_template("booking.html",user=current_user,data=all_data,email=email)
    

@views.route("/bookingForm",methods=['GET','POST'])
@login_required
def bookingForm():
    if request.method == 'POST':
        name=request.form['name']
        email=request.form['email']
        address=request.form['address']
        date=request.form['date']
        phne=request.form['phne']
        wemail=request.form['wemail']
        username=current_user.username
        status="Pending"
        from datetime import datetime
        import datetime

        Db_date=bookingdb.query.filter_by(date=date,status="Accepted").first()
        t_date= datetime.date.today()
        cur=datetime.datetime.strptime(date,'%Y-%m-%d')
        c_date=cur.date()
        # print(c_date)
        # print("dvdcdc",wemail)
        if(c_date<t_date):
            flash("Enter correct date")
        else:
            my_data=bookingdb(name,email,address,phne,date,username,status,wemail)
            db.session.add(my_data)
            db.session.commit()
            flash("Data send to admin...Wait for admin's response")
        return redirect(url_for('views.booking',user=current_user))

# admin

@views.route("/bookingAdmin")
def bookingAdmin():
    all_data=bookingdb.query.all()
    return render_template("bookingAdmin.html",data=all_data,user=current_user)


@views.route("/packageAdmin")
def packageAdmin():
    return render_template("packageAdmin.html",user=current_user)


@views.route("/galleryAdmin")
def galleryAdmin():
    all_data=galleryImageUpload.query.all()
    return render_template("galleryAdmin.html",data=all_data,user=current_user)

ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg' ,'gif'])

def allowed_file(filename):
    return '.' in filename and filename.rsplit(".",1)[1].lower() in ALLOWED_EXTENSIONS

@views.route("/galleryImage",methods=['post'])
@login_required
def galleryImage():
    if request.method == 'POST':
        file = request.files['inputFile']

        if file.filename == '':
            flash("Please select an image")
            return redirect(url_for('views.galleryAdmin',user=current_user))
        
        if file and allowed_file(file.filename):
            name = file.filename
            data = file.read()
            final_pic=base64.b64encode(data).decode('ascii')
            upload = galleryImageUpload(name , final_pic)
            db.session.add(upload)
            db.session.commit()
            return redirect(url_for('views.galleryAdmin',user=current_user))
        else:
            flash("Only images are allowed")
            return redirect(url_for('views.galleryAdmin',user=current_user))
 
#accepting and rejecting orders

@views.route("/acceptConcept/<id>")
def acceptConcept(id):
    my_data=bookingdb.query.get(id)
    subject="Worker Verification"
    msg="Your request have been Accepted by Helpcenter"
    msg1="You have a work now "
    # msg=my_data.email,my_data.name
    msg3=my_data.email
    # print(msg3)
    message=Message(subject,sender="kiruthickkumark.20cse@kongu.edu",recipients=[my_data.email])
    message1=Message(subject,sender="kiruthickkumark.20cse@kongu.edu",recipients=[my_data.wemail])
    message1.body=msg1
    message.body=msg
    mail.send(message)
    mail.send(message1)
    # mail.send(message1)
    success ="message send"
    my_data.status="Accepted"
    db.session.commit()
    return redirect(url_for('views.bookingAdmin',user=current_user,success=success))

@views.route("/rejectConcept/<id>")
def rejectConcept(id):
    my_data=bookingdb.query.get(id)
    my_data.status="Rejected"
    db.session.commit()
    return redirect(url_for('views.bookingAdmin',user=current_user))

@views.route("/cancelConcept/<id>")
def cancelConcept(id):
    my_data=bookingdb.query.get(id)
    my_data.status="Canceled"
    db.session.commit()
    return redirect(url_for('views.booking',user=current_user))


# @views.route('/workerdata',methods=['GET','POST'])
# @login_required
# def workerdata():
#     # if request.method =='POST':
    #     cusid=request.form['cusid']
    #     username=request.form['uname']
        # firstname =request.form('fname')
        # email=request.form('email')
        # address=request.form('address')
        # work=request.form('work')
        # houseno=request.form('houseno')
        # pincode=request.form('pincode')
        # city=request.form('city')
        # distric=request.form('distric')
        # state=request.form('state')
        # file1 = request.files['image1']
        # data1 = file1.read()
        # render_file1 = render_picture(data1)
        # subject="WORKER VERFICATION"
        # msg="NOW YOU WAS HELPCENTER WORKER"
        # from .models import Data
        # data=Data.query.filter_by(cusid=cusid).first()
        # if data:
        #     flash("alredy")
        #     print("already")

website/templates/gallery.html
{%extends "layout.html"%}
{% block content %}
    <section class="gallery" id="gallery">
        <div class="gallery-content">
            <div class="section-title">
                <h1><i>gallery</i></h1>
                <div class="gallery-list-img">
                  {% for row in data %}
                     <div class="gallery-img">
                        <img src="data:;base64,{{ row.final_img }}" width="300px" height="300px">
                     </div>
                  {%endfor%}
            </div>
        </div>
    
    </section>
{%endblock%}

website/templates/galleryAdmin.html
{%extends "layoutAdmin.html"%}
{% block content %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
          <span aria-hidden="true">x</span>
        </button>
        {{message}}
      </div>
          
    {% endfor %}
  {%endif %}
{% endwith %}

<section class="gallery" id="gallery">
  <div class="gallery-content">
      <div class="section-title">
          <h1><i>gallery</i></h1>
          <div class="gallery-list-img">
            {% for row in data %}
              <div class="gallery-img">
                <img src="data:;base64,{{ row.final_img }}" width="300px" height="300px">
              </div>
            {%endfor%}
      </div>
  </div>

</section>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Add Image
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form method="post" action="{{url_for('views.galleryImage')}}"  enctype="multipart/form-data">
                <div class="form-group">
                  <label for="exampleFormControlFile1">Example file input</label>
                  <input type="file" class="form-control-file" id="exampleFormControlFile1" name="inputFile">
                </div>
                <button type="submit" class="btn btn-primary">Upload</button>
            </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div>
{%endblock%}

website/templates/home.html
 {%extends "layout.html"%}
{% block content %}
    
 <!-- <section class="home">
    <div class="container">
        <div class="home-img">
        </div>
        <div class="home-content">
            <h1><span>Find your worker </span><span>on online</span></h1>
        </div>
    </div>
     -->
<!-- <!DOCTYPE html>
<html lang="en"> -->

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
  <title>WORKERS PLATEFORM</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <link rel="stylesheet" href=
  "https://fonts.googleapis.com/icon?family=Material+Icons" />
  </head>
  <!-- Favicons -->
  <link href="/website/static/images/child care.jpg" rel="icon">
  <link href="/website/static/images/cook.jpg" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet"> -->

  <!-- Vendor CSS Files -->
  <!-- <link href="/website/static/css/aos.css" rel="stylesheet">
  <link href="/website/static/css/bootstrap.min.css" rel="stylesheet">
  <link href="/website/static/css/bootstrap-icons.css" rel="stylesheet">
  <link href="/website/static/css/boxicons.min.css" rel="stylesheet">
  <link href="/website/static/css/glightbox.min.css" rel="stylesheet">
  <link href="/website/static/css/swiper-bundle.min.css" rel="stylesheet"> -->

  <!-- Template Main CSS File -->
  <link href="../static/css/home.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: BizLand - v3.9.1
  * Template URL: https://bootstrapmade.com/bizland-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <!-- /**
* Template Name: BizLand - v3.9.1
* Template URL: https://bootstrapmade.com/bizland-bootstrap-business-template/
* Author: BootstrapMade.com
* License: https://bootstrapmade.com/license/
*/

/*--------------------------------------------------------------
# General
--------------------------------------------------------------*/ -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">
        

      <h1 class="logo"><a href="{{url_for('views.home')}}"><span>Helpcenter</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt=""></a>-->

      

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container" data-aos="zoom-out" data-aos-delay="100">
      <h1>Welcome to <span>Helpcenter</span></h1>
      <h2>Using thise application we can find the workers </h2>
      <div class="d-flex">
        <a href="{{url_for('views.services')}}" class="btn-get-started scrollto">Get Started</a>
        <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="glightbox btn-watch-video"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    

            

         

    <!-- ======= Counts Section ======= -->
    

   

  <!-- ======= Footer ======= -->
  <footer id="footer">

    

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3><span>Helpcenter</span></h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Social Networks</h4>
            <p>Cras fermentum odio eu feugiat lide par naso tierra videa magna derita valies</p>
            <div class="social-links mt-3">
                <!-- <a href="#" class="bx bxl-facebook"></a>
                <a href="#" class="fa fa-pinterest"></a>
                <a href="#" class="fa fa-reddit"></a> -->
              <a href="#" class="twitter"><i class="fa-brands fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa-brands fa-facebook"></i></i></a>
              <a href="#" class="instagram"><i class="fa-brands fa-instagram"></i></i></a>
              <a href="#" class="google-plus"><i class="fa-brands fa-skype"></i></i></a>
              <a href="#" class="linkedin"><i class="fa-brands fa-linkedin"></i></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Helpcenter</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bizland-bootstrap-business-template/ -->
        <!-- Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
      </div>
    </div>
  </footer><!-- End Footer -->

  <!-- <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <!-- <script src="/website/static/images/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="/website/static/images/vendor/aos/aos.js"></script>
  <script src="/website/static/images/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/website/static/images/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/website/static/images/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/website/static/images/vendor/swiper/swiper-bundle.min.js.map"></script> -->
  <!-- <script src="assets/vendor/waypoints/noframework.waypoints.js"></script> -->
  <!-- <script src="/website/static/images/vendor/php-email-form/validate.js"></script> -->



  <!-- Template Main JS File -->
  <!-- <script src="/website/static/js/main.js"></script> --> 

</body>
{% endblock %} 

</html>

website/templates/layout.html
<!-- <!doctype html>
<html lang="en">
   <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>HOME</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Nunito:ital,wght@0,200;1,500;1,700&display=swap" rel="stylesheet">

    <!-- navBar styles -->
    <!-- <link href="{{url_for('static',filename='css/.css')}}" rel="stylesheet"> -->
    <link href="{{url_for('static',filename='css/home.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename='css/home.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/navBar.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/home.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/services.css')}}">

    <!-- font awsome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>
  <body>
    <!--Navbar section-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mr-auto">
            <li class="nav-item ">
              <a class="nav-link " href="{{url_for('views.home')}}" >Home </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.services')}}">Services</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.getinfo')}}">workers</a>
          </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.booking')}}">Booking</a>
            </li> -->
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{{url_for('views.logout')}}">logout</a>
            </li>

            {% else %}
            <li class="nav-item" >
              <a href="{{url_for('views.login')}}" class="login">
                LOGIN
              </a>


            {% endif %}
            </li>
          </ul>

        </div>
      </nav>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <div>
        {% block content%}
        {%endblock%}
    </div>
  </body>
</html> -->

website/templates/layoutAdmin.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>HOME</title>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Nunito:ital,wght@0,200;1,500;1,700&display=swap" rel="stylesheet">

    <!-- navBar styles -->
    <link href="{{url_for('static',filename='css/booking.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename='css/gallery.css')}}" rel="stylesheet">
    <link href="{{url_for('static',filename='css/home.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/navBar.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/package.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/services.css')}}">

    <!-- font awsome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    
</head>
  <body>
    <!--Navbar section-->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.galleryAdmin')}}">Gallery</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.workerdataAdmin')}}">workerdata</a>
          </li>
          
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.bookingAdmin')}}">Booking</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{{url_for('views.logout')}}">logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{{url_for('views.login')}}" class="login">
                LOGIN
              </a>
            </li>
            {% endif %}
          </ul>

        </div>
      </nav>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <div>
        {% block content%}
        {%endblock%}
    </div>
  </body>
</html>

website/templates/update.html
<form action="{{url_for('views.update')}}" method = "POST">
    <p>name <input type = "text" name = "name" value=""/></p>
    <p> </p>
    <p>age <input type = "integer" name = "status"  value=""/></p>
    <p>position <input type = "text" name = "email" value=""/></p>
    <p><input type = "submit" value = "update" /></p>
  </form>